mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    # MyBatis 字符编码配置
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
    # 确保 MyBatis 使用 UTF-8
    character-set-results: UTF-8

server:
  port: 8081
  # 服务器字符编码配置
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    # 重要：使用 utf8mb4 字符集
    url: jdbc:mysql://mysql-db:3306/myblog_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8mb4&useUnicode=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: DatebookHikariCP

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # HTTP 编码配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

  # 消息编码配置
  messages:
    encoding: UTF-8

  # Thymeleaf 模板配置
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html;charset=UTF-8
    # 禁用缓存，便于开发调试
    cache: false

  # Web 相关配置
  web:
    locale: zh_CN
    locale-resolver: fixed

# 日志配置
logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    org.springframework.web: DEBUG
    com.zaxxer.hikari: DEBUG